### ISSUE TITLE
data-pool push/update do not work

### ISSUE THREAD

**Issue by kaztakata** [celonis/content-cli#73]
I checked data-pool command using content-cli latest version 0.1.3.
Pull command is working correctly, then I tried to upload this downloaded json file to another team.

First I tried push command with file and profile option, then I got server error `error:   {"reference":"df400d88-4a21-44bc-b6a4-e42ccd7092b4","message":"Something went wrong while handling the request. Please contact Celonis customer support. Celonis Support ID: df400d88-4a21-44bc-b6a4-e42ccd7092b4","shortMessage":"Celonis Support ID: df400d88-4a21-44bc-b6a4-e42ccd7092b4"}`. I found that just data-pool is created to target team but components in the pool (datajobs and data models etc.) are not uploaded.

Second I tried update command with file, profile, and pool id that is created by first trial, then I got server error `error:   {"errors":[{"attribute":"name","error":"Name must be unique","errorCode":"name.unique","additionalInfo":"Planio v1"}]}`. And pool components are not uploaded too.

Is it different from your expected behavior ? I did not find documentation regarding data pool.

**Comment by kaztakata** [comment]
Dear @promeris,

May I ask you regarding this topic ?

**Comment by promeris** [comment]
hey @kaztakata, hope you are doing well. For the first error message, it is advisable in this case to contact Celonis Customer Support and include the Celonis Support id from the error message because it's not something to do with the cli. As for the second message, it seems that a data pool is already existing in the team with that name, so you would need to change the name in the file. 

I'm sorry I can't be of more help here, but opening a ticket with Celonis' Customer Support should be the way to go.

**Comment by kaztakata** [comment]
@promeris 
Thanks I will go to Service desk.
